services:
  mtrabbitmq:
    image: masstransit/rabbitmq:latest
    ports:
     - "5672:5672"
     - "15672:15672"
    healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:15672"]
        interval: 30s
        timeout: 10s
        retries: 5

  samplemt.service:
    image: ${DOCKER_REGISTRY-}samplemtservice
    build:
      context: .
      dockerfile: SampleMT.Service/Dockerfile
    depends_on:
      mtrabbitmq:
        condition: service_healthy
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:8080/healthz || exit 1
      interval: 10s
      timeout: 5s
    environment:      
      Modules__0__name: "MassTransit"
      Modules__0__provider__name: "RabbitMQ"
      Modules__0__provider__host: "mtrabbitmq"
      Modules__0__provider__virtualHost: "/"
      Modules__0__provider__user: "guest"
      Modules__0__provider__password: "guest"
      Modules__0__subModules__0: "Processor"
      Modules__1: "WebApi"